### ISSUE TITLE
Receive Car state

### ISSUE THREAD

**Issue by avrpic8** [lacour-vincent/wifi-car-esp8266#1]
Hi man,
Thanks for great project.
How to get state car in android log information.
I see this message when press arrows ->
Response{protocol=http/1.1, code=200, message=OK, url=http://192.168.4.1:8080/move?dir=R}
but in arduino code you write   ''server.send(200, "text / plain", "Turn: Right");''

but I want get state of car in android app, how can I do.

**Comment by lacour-vincent** [comment]
Hi, I'm sorry to answer so late. The android application log only the status of the request:
```Log.i("Response", response.code().toString())```
If you want to expose data to the client, you should probably update the code of the car and the application to send and serialize data using:
https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WebServer
https://github.com/google/gson

Hope it helps !
