### ISSUE TITLE
Alamofire-prefix.pch cannot be found

### ISSUE THREAD

**Issue by seb201** [lacour-vincent/wifi-car-esp8266#2]
Hello,

i have try to build the iOS Version, but only get a error:

Build input file cannot be found: '/Users/seb201/Documents/Arduino/Projekte/ArduBoot/WIFICar/wifi-car-esp8266-master/ios/Pods/Target Support Files/Alamofire/Alamofire-prefix.pch'

Where can I get Alamofire-prefix.pch file?

<img width="1512" alt="Bildschirmfoto 2020-04-11 um 16 41 07" src="https://user-images.githubusercontent.com/35576062/79046802-4447cb00-7c13-11ea-8ecf-a59796aee749.png">

Can someone help me?

Greetings

**Comment by lacour-vincent** [comment]
Hi seb ! This error is about Alamofire dependency. To build the iOS app, you should:
- install https://cocoapods.org/
- ```git clone https://github.com/lacour-vincent/wifi-car-esp8266.git```
- ```cd wifi-car-esp8266/ios```
- ```pod install```
- open xcode and open another project and select : ```wifi-car-esp8266/ios/wificaresp8266.xcworkspace```
- then you should able to build the project with ```cmd + B```

Hope it helps !

**Comment by seb201** [comment]
Thank you, now it works well
