### ISSUE TITLE
Adding Servo and Buzzer

### ISSUE THREAD

**Issue by shahriarshafin** [lacour-vincent/wifi-car-esp8266#4]
I want to add a Servo and Buzzer. Is it possible to do?

**Comment by RemonEssa** [comment]
I want to use L298N instead of L293 motor shield

**Comment by Tech-TX** [comment]
It's open-source... knock yourselves out and do with it what you wish.  Modify and tweak at will!

Don't expect the author to design your spin-off projects for you, though.  That's just rude.
